loglevel = "ERROR"

[backends]
[backends.nasweb]
    [backends.nasweb.servers.nasweb]
        url = "http://birdwell:5000"

[frontends]
    [frontends.domain]
        backend = "nasweb"
    [frontends.domain.routes.domain]
        rule = "Host:birdwell.rdshft.de"
